using eyecandy;

/*

WebAudio uses a bizarre time-smoothing factor, and allegedly also has clipping.
None of this seems to work when visually comparing to Shadertoy (check out the
"frag" demo for details).

This demo shows the difference between a normal FFD Decibels calculation (top)
versus what is generated by WebAudio (bottom).

Hit ESC to exit.
 
Stick with 16:9 aspect-ratio resolutions for consistency when going full-screen
https://www.studio1productions.com/Articles/16x9-Resolution.htm

*/

namespace demo
{
    internal class Decibels
    {
        public static async Task Demo()
        {
            Console.WriteLine("\n\nwebaudio: Real FFT dBs (top) vs. WebAudio smoothed pseudo-dBs (bottom)");

            var config = new EyeCandyCaptureConfig();

            if (Program.UseMetronome) config.LoopbackApi = LoopbackApi.Metronome;

            if (Program.WindowsUseOpenALSoft) config.LoopbackApi = LoopbackApi.OpenALSoft;

            var windowConfig = new EyeCandyWindowConfig();
            windowConfig.OpenTKNativeWindowSettings.Title = "Eyecandy Demo: Decibels / WebAudio comparison";
            windowConfig.OpenTKNativeWindowSettings.ClientSize = (960, 540);
            windowConfig.StartFullScreen = Program.StartFullScreen;

            // remember Linux is case-sensitive...
            windowConfig.VertexShaderPathname = "Decibels/decibels.vert";
            windowConfig.FragmentShaderPathname = "Decibels/decibels.frag";

            var win = new DecibelsWindow(windowConfig, config);
            win.Focus();
            win.Run();
            win.Dispose();
        }
    }
}
